server:
  port: 9090
spring:
  application:
    name: yuntian-cloud-stream-producer
  cloud:
    stream:
      binders: # 绑定MQ服务信息（此处我们是RabbitMQ）
        yuntianRabbitBinder: # 给Binder定义的名称，用于后面的关联
          type: rabbit # MQ类型，如果是Kafka的话，此处配置kafka
          environment: # MQ环境配置（用户名、密码等）
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 关联整合通道和binder对象
        output: # output是我们定义的通道名称，此处不能乱改
          destination: yuntianExchange # 要使用的Exchange名称（消息队列主题名称）
          content-type: text/plain # application/json # 消息类型设置，比如json
          binder: yuntianRabbitBinder  # 关联MQ服务

eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://eureka2001.yuntian.com:2001/eureka/,http://eureka2003.yuntian.com:2003/eureka/
